version: '3.8'
services:
  mongodb:
    image: mongo
    logging:
      driver: "none"
    ports:
      - '27017:27017'
    networks:
      - syncme-network
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: prod
    ports:
      - '50051:50051'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/syncme
    networks:
      - syncme-network

  test:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: tests
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/syncme
    networks:
      - syncme-network

networks:
  syncme-network:
    driver: bridge